apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-demo-deployment
  labels:
    app: kube-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-demo
  template:
    metadata:
      labels:
        app: kube-demo
    spec:
      containers:
        - name: kube-demo
          image: edanimark/kube-demo:latest
          ports:
            - containerPort: 8080
