apiVersion: v1
kind: Service
metadata:
  name: kube-demo-service
spec:
  type: NodePort
  selector:
    app: kube-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
